package com.jnj.mse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AggregateCount implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long count;

	public AggregateCount() {
	}

	public java.lang.Long getCount() {
		return this.count;
	}

	public void setCount(java.lang.Long count) {
		this.count = count;
	}

	public AggregateCount(java.lang.Long count) {
		this.count = count;
	}

}