package com.jnj.mse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AggregateMaxInteractionDate implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.jnj.mse.MaxInteractionDate max;

	public AggregateMaxInteractionDate() {
	}

	public com.jnj.mse.MaxInteractionDate getMax() {
		return this.max;
	}

	public void setMax(com.jnj.mse.MaxInteractionDate max) {
		this.max = max;
	}

	public AggregateMaxInteractionDate(com.jnj.mse.MaxInteractionDate max) {
		this.max = max;
	}

}