package com.jnj.mse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LastInteractionDate implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.jnj.mse.AggregateMaxInteractionDate aggregate;

	public LastInteractionDate() {
	}

	public com.jnj.mse.AggregateMaxInteractionDate getAggregate() {
		return this.aggregate;
	}

	public void setAggregate(com.jnj.mse.AggregateMaxInteractionDate aggregate) {
		this.aggregate = aggregate;
	}

	public LastInteractionDate(
			com.jnj.mse.AggregateMaxInteractionDate aggregate) {
		this.aggregate = aggregate;
	}

}