package com.jnj.mse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MaxInteractionDate implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String interaction_date;

	public MaxInteractionDate() {
	}

	public java.lang.String getInteraction_date() {
		return this.interaction_date;
	}

	public void setInteraction_date(java.lang.String interaction_date) {
		this.interaction_date = interaction_date;
	}

	public MaxInteractionDate(java.lang.String interaction_date) {
		this.interaction_date = interaction_date;
	}

}