package com.jnj.mse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule1Fact implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.jnj.mse.MSL msl;
	private com.jnj.mse.KeyIndividual key_individual;
	private java.lang.String engagement_frequency;
	private com.jnj.mse.InteractionCount submitted_interactions;
	private com.jnj.mse.InteractionCount planned_interactions;
	private com.jnj.mse.LastInteractionDate last_interaction_date;

	private com.jnj.mse.Rule1Result result;

	public Rule1Fact() {
	}

	public com.jnj.mse.MSL getMsl() {
		return this.msl;
	}

	public void setMsl(com.jnj.mse.MSL msl) {
		this.msl = msl;
	}

	public com.jnj.mse.KeyIndividual getKey_individual() {
		return this.key_individual;
	}

	public void setKey_individual(com.jnj.mse.KeyIndividual key_individual) {
		this.key_individual = key_individual;
	}

	public java.lang.String getEngagement_frequency() {
		return this.engagement_frequency;
	}

	public void setEngagement_frequency(java.lang.String engagement_frequency) {
		this.engagement_frequency = engagement_frequency;
	}

	public com.jnj.mse.InteractionCount getSubmitted_interactions() {
		return this.submitted_interactions;
	}

	public void setSubmitted_interactions(
			com.jnj.mse.InteractionCount submitted_interactions) {
		this.submitted_interactions = submitted_interactions;
	}

	public com.jnj.mse.InteractionCount getPlanned_interactions() {
		return this.planned_interactions;
	}

	public void setPlanned_interactions(
			com.jnj.mse.InteractionCount planned_interactions) {
		this.planned_interactions = planned_interactions;
	}

	public com.jnj.mse.LastInteractionDate getLast_interaction_date() {
		return this.last_interaction_date;
	}

	public void setLast_interaction_date(
			com.jnj.mse.LastInteractionDate last_interaction_date) {
		this.last_interaction_date = last_interaction_date;
	}

	public com.jnj.mse.Rule1Result getResult() {
		return this.result;
	}

	public void setResult(com.jnj.mse.Rule1Result result) {
		this.result = result;
	}

	public Rule1Fact(com.jnj.mse.MSL msl,
			com.jnj.mse.KeyIndividual key_individual,
			java.lang.String engagement_frequency,
			com.jnj.mse.InteractionCount submitted_interactions,
			com.jnj.mse.InteractionCount planned_interactions,
			com.jnj.mse.LastInteractionDate last_interaction_date,
			com.jnj.mse.Rule1Result result) {
		this.msl = msl;
		this.key_individual = key_individual;
		this.engagement_frequency = engagement_frequency;
		this.submitted_interactions = submitted_interactions;
		this.planned_interactions = planned_interactions;
		this.last_interaction_date = last_interaction_date;
		this.result = result;
	}

}