package com.jnj.mse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule1Config implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean enabled;

	private java.lang.String currentDate;

	private java.lang.Integer maintainTargetInteractions;

	private java.lang.Integer developTargetInteractions;

	private java.lang.Integer frequentTargetInteractions;

	private java.math.BigDecimal engagementAchievementThreshold;

	public Rule1Config() {
	}

	public java.lang.Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(java.lang.Boolean enabled) {
		this.enabled = enabled;
	}

	public java.lang.String getCurrentDate() {
		return this.currentDate;
	}

	public void setCurrentDate(java.lang.String currentDate) {
		this.currentDate = currentDate;
	}

	public java.lang.Integer getMaintainTargetInteractions() {
		return this.maintainTargetInteractions;
	}

	public void setMaintainTargetInteractions(
			java.lang.Integer maintainTargetInteractions) {
		this.maintainTargetInteractions = maintainTargetInteractions;
	}

	public java.lang.Integer getDevelopTargetInteractions() {
		return this.developTargetInteractions;
	}

	public void setDevelopTargetInteractions(
			java.lang.Integer developTargetInteractions) {
		this.developTargetInteractions = developTargetInteractions;
	}

	public java.lang.Integer getFrequentTargetInteractions() {
		return this.frequentTargetInteractions;
	}

	public void setFrequentTargetInteractions(
			java.lang.Integer frequentTargetInteractions) {
		this.frequentTargetInteractions = frequentTargetInteractions;
	}

	public java.math.BigDecimal getEngagementAchievementThreshold() {
		return this.engagementAchievementThreshold;
	}

	public void setEngagementAchievementThreshold(
			java.math.BigDecimal engagementAchievementThreshold) {
		this.engagementAchievementThreshold = engagementAchievementThreshold;
	}

	public Rule1Config(java.lang.Boolean enabled, java.lang.String currentDate,
			java.lang.Integer maintainTargetInteractions,
			java.lang.Integer developTargetInteractions,
			java.lang.Integer frequentTargetInteractions,
			java.math.BigDecimal engagementAchievementThreshold) {
		this.enabled = enabled;
		this.currentDate = currentDate;
		this.maintainTargetInteractions = maintainTargetInteractions;
		this.developTargetInteractions = developTargetInteractions;
		this.frequentTargetInteractions = frequentTargetInteractions;
		this.engagementAchievementThreshold = engagementAchievementThreshold;
	}

}