package com.jnj.mse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule1Result implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long actual_interactions;
	private java.lang.Long target_interactions;
	private java.math.BigDecimal engagement_achievement;
	private java.math.BigDecimal year_elapsed_percent;
	private java.lang.String suggestion;

	public Rule1Result() {
	}

	public java.lang.Long getActual_interactions() {
		return this.actual_interactions;
	}

	public void setActual_interactions(java.lang.Long actual_interactions) {
		this.actual_interactions = actual_interactions;
	}

	public java.lang.Long getTarget_interactions() {
		return this.target_interactions;
	}

	public void setTarget_interactions(java.lang.Long target_interactions) {
		this.target_interactions = target_interactions;
	}

	public java.math.BigDecimal getEngagement_achievement() {
		return this.engagement_achievement;
	}

	public void setEngagement_achievement(
			java.math.BigDecimal engagement_achievement) {
		this.engagement_achievement = engagement_achievement;
	}

	public java.math.BigDecimal getYear_elapsed_percent() {
		return this.year_elapsed_percent;
	}

	public void setYear_elapsed_percent(
			java.math.BigDecimal year_elapsed_percent) {
		this.year_elapsed_percent = year_elapsed_percent;
	}

	public java.lang.String getSuggestion() {
		return this.suggestion;
	}

	public void setSuggestion(java.lang.String suggestion) {
		this.suggestion = suggestion;
	}

	public Rule1Result(java.lang.Long actual_interactions,
			java.lang.Long target_interactions,
			java.math.BigDecimal engagement_achievement,
			java.math.BigDecimal year_elapsed_percent,
			java.lang.String suggestion) {
		this.actual_interactions = actual_interactions;
		this.target_interactions = target_interactions;
		this.engagement_achievement = engagement_achievement;
		this.year_elapsed_percent = year_elapsed_percent;
		this.suggestion = suggestion;
	}

}